---
name: static-website
'on':
  pull_request:
  push:
    branches:
      - main
      - test-cache
#  schedule:
#    - cron: "0 2 * * *"
env:
  ID_DOCKER: "docker19191919"
  IMAGE_NAME: "staticwebsite"
  IMAGE_TAG: "latest"
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"

jobs:
  build:
    name: BUILD DOCKER IMAGE
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Build Image
        run: | 
          docker build -t ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG .
          docker save ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG > $IMAGE_NAME
          echo "IMAGE_NAME=staticwebsite" >> $GITHUB_ENV
      - name: Cache artefact
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}

  push:
    name: PUSH IMAGE ON DOCKERHUB
    needs: run-and-test
    runs-on: ubuntu-latest
    steps:    
      - name: Download workspace from job build
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}
      - name: Login and Push Image on docker hub
        run: |
          docker load < $IMAGE_NAME
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u $ID_DOCKER --password-stdin
          docker push ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG          
          
        
