run-and-test:
  name: RUN AND TEST CONTAINER
  needs: build
  runs-on: ubuntu-latest
  steps:  
    - name: Download workspace from job build
      uses: actions/cache@v3
      with:
        key: image
        path: ${{ env.IMAGE_NAME }}
    - name: Run container based on built image
      run: |
        docker load < ${DOCKERHUB_ID}/$IMAGE_NAME:$IMAGE_TAG
        docker run --name $IMAGE_NAME -d -p ${APP_EXPOSED_PORT}:${APP_CONTAINER_PORT} -e PORT=$APP_CONTAINER_PORT ${DOCKERHUB_ID}/$IMAGE_NAME:$IMAGE_TAG
        sleep 5
